// vue-frontend/app/components/Cart.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import {
  getCartItems,
  clearCart,
  updateCartItem,
  removeCartItem,
} from "~/services/cartService";
import CartItem from "~/components/CartItem.vue";
import type { CartItemResponseDto } from "~/types/cart";
import { useRouter } from "#app";
import { useToast } from "vue-toastification";

const cart = ref<CartItemResponseDto[]>([]);
const timeoutIds = ref<Record<number, ReturnType<typeof setTimeout>>>({});
const router = useRouter();
const toast = useToast();

const cartTotal = computed(() =>
  cart.value.reduce((sum, item) => sum + item.price * item.quantity, 0)
);
const formattedTotal = computed(() => cartTotal.value.toFixed(2));

onMounted(loadCart);

async function loadCart() {
  try {
    cart.value = await getCartItems();
  } catch (err) {
    console.error("Kunne ikke hente handlekurv:", err);
  }
}

async function handleClearCart() {
  try {
    await clearCart();
    cart.value = [];
    toast.success("Handlekurven ble tømt!");
  } catch (err) {
    console.error("Kunne ikke tømme handlekurven:", err);
  }
}

async function handleCheckoutCart() {
  try {
    await router.push("/checkout/delivery");
  } catch (err) {
    console.error("Kunne ikke gå til checkout", err);
  }
}

// Debounced oppdatering av antall
function handleUpdateQuantity(itemId: number, newQuantity: number) {
  if (newQuantity <= 0) {
    handleRemove(itemId);
    return;
  }

  cart.value = cart.value.map((item) =>
    item.id === itemId ? { ...item, quantity: newQuantity } : item
  );
  toast.success("Handlekurven oppdatert!");

  if (timeoutIds.value[itemId]) {
    clearTimeout(timeoutIds.value[itemId]);
  }

  const id = setTimeout(async () => {
    try {
      const updated = await updateCartItem(itemId, newQuantity);
      cart.value = cart.value.map((item) =>
        item.id === updated.id ? updated : item
      );
    } catch (err) {
      console.error("Kunne ikke oppdatere antall:", err);
    }
  }, 500);

  timeoutIds.value[itemId] = id;
}

async function handleRemove(itemId: number) {
  try {
    await removeCartItem(itemId);
    cart.value = cart.value.filter((item) => item.id !== itemId);
    toast.success("Produkt fjernet!");
  } catch (err) {
    console.error("Kunne ikke fjerne vare:", err);
  }
}
</script>

<template>
  <div class="p-8 border-4 border-gray-800">
    <h2 class="mb-4 text-2xl font-bold">Handlekurv</h2>

    <template v-if="cart.length === 0">
      <p>Handlekurven er tom</p>
    </template>

    <template v-else>
      <ul class="mb-6 space-y-4">
        <CartItem
          v-for="item in cart"
          :key="item.id"
          :item="item"
          @update-quantity="handleUpdateQuantity"
          @remove="handleRemove"
        />
      </ul>

      <div class="mb-4 font-bold text-lg flex justify-center">
        Totalpris: {{ formattedTotal }} kr
      </div>

      <div class="flex justify-between">
        <button
          @click="handleCheckoutCart"
          class="px-4 py-2 text-white bg-green-600 rounded hover:bg-green-700"
        >
          Bestill
        </button>
        <button
          @click="handleClearCart"
          class="px-4 py-2 text-white bg-red-600 rounded hover:bg-red-900"
        >
          Tøm handlekurv
        </button>
      </div>
    </template>
  </div>
</template>

// frontend/src/components/Cart.tsx
"use client";
import { useEffect, useState } from "react";
import {
  getCartItems,
  clearCart,
  updateCartItem,
  removeCartItem,
} from "@/services/cartApi";
import CartItem from "./CartItem";
import toast from "react-hot-toast";
import { useRouter } from "next/navigation";
import { CartItemResponseDto } from "@/types/Cart";

export default function Cart() {
  const [cart, setCart] = useState<CartItemResponseDto[]>([]);
  const [timeoutIds, setTimeoutIds] = useState<Record<number, NodeJS.Timeout>>(
    {}
  );
  const cartTotal = cart.reduce(
    (sum, item) => sum + item.price * item.quantity,
    0
  );
  const formattedTotal = cartTotal.toFixed(2);
  const router = useRouter();

  // Hent cart items ved første render
  useEffect(() => {
    loadCart();
  }, []);

  async function loadCart() {
    try {
      const items = await getCartItems();
      setCart(items);
    } catch (err) {
      console.error("Kunne ikke hente handlekurv:", err);
    }
  }

  async function handleClearCart() {
    try {
      await clearCart();
      setCart([]);
      toast.success("Handlekurven ble tømt!");
    } catch (err) {
      console.error("Kunne ikke tømme handlekurven:", err);
    }
  }

  async function handleCheckoutCart() {
    try {
      router.push("/checkout/delivery");
    } catch (err) {
      console.error("Kunne ikke gå til checkout", err);
    }
  }

  // Debounced oppdatering av antall
  function handleUpdateQuantity(itemId: number, newQuantity: number) {
    console.log("Ny quantity:", newQuantity);
    if (newQuantity <= 0) {
      console.log("Fjerner produkt med id:", itemId);
      handleRemove(itemId);
      return;
    }

    setCart((prev) =>
      prev.map((item) =>
        item.id === itemId ? { ...item, quantity: newQuantity } : item
      )
    );
    toast.success("Handlekurven oppdatert!");

    if (timeoutIds[itemId]) {
      clearTimeout(timeoutIds[itemId]);
    }

    const id = setTimeout(async () => {
      try {
        const updated = await updateCartItem(itemId, newQuantity);
        setCart((prev) =>
          prev.map((item) => (item.id === updated.id ? updated : item))
        );
      } catch (err) {
        console.error("Kunne ikke oppdatere antall:", err);
      }
    }, 500);

    setTimeoutIds((prev) => ({ ...prev, [itemId]: id }));
  }

  async function handleRemove(itemId: number) {
    try {
      await removeCartItem(itemId);
      setCart((prev) => prev.filter((item) => item.id !== itemId));
      toast.success("Produkt fjernet!");
    } catch (err) {
      console.error("Kunne ikke fjerne vare:", err);
    }
  }

  return (
    <div className="p-8 border-4 border-gray-800">
      <h2 className="mb-4 text-2xl font-bold">Handlekurv</h2>
      {cart.length === 0 ? (
        <p>Handlekurven er tom</p>
      ) : (
        <>
          <ul className="mb-6 space-y-4">
            {cart.map((item) => (
              <CartItem
                key={item.id}
                item={item}
                onUpdateQuantity={handleUpdateQuantity}
                onRemove={handleRemove}
              />
            ))}
          </ul>
          <div className="mb-4 font-bold text-lg flex justify-center">
            Totalpris: {formattedTotal} kr
          </div>
          <div className="flex justify-between">
            <button
              onClick={handleCheckoutCart}
              className="px-4 py-2 text-white bg-green-600 rounded hover:bg-green-700"
            >
              Bestill
            </button>
            <button
              onClick={handleClearCart}
              className="px-4 py-2 text-white bg-red-600 rounded hover:bg-red-900"
            >
              Tøm handlekurv
            </button>
          </div>
        </>
      )}
    </div>
  );
}
