// react-frontend/src/modals/RegisterModal.tsx
"use client";
import { useState, useRef, useEffect } from "react";
import { registerUser } from "@/services/userApi";
import { useRouter } from "next/navigation";

interface RegisterModalProps {
  open: boolean;
  onClose: () => void;
}

export default function RegisterModal({ open, onClose }: RegisterModalProps) {
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const router = useRouter();
  const nameInputRef = useRef<HTMLInputElement>(null);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();

    if (!username || !email || !password) {
      setError("Alle felt må fylles inn");
      return;
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      setError("Ugyldig e-postadresse");
      return;
    }

    try {
      await registerUser({ username, email, password });
      setError("");
      setUsername("");
      setEmail("");
      setPassword("");
      onClose();
      router.push("/");
    } catch (err) {
      console.error("Kunne ikke registrere bruker:", err);
      setError("Feil ved registrering av ny bruker");
    }
  }

  useEffect(() => {
    if (open && nameInputRef.current) {
      nameInputRef.current.focus();
    }
  }, [open]);

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50">
      <div className="w-full max-w-sm p-6 text-center bg-gray-800 rounded shadow-lg">
        <h2 className="mb-4 text-xl font-bold">Registrer ny bruker</h2>
        {error && <p className="mb-2 text-red-500">{error}</p>}
        <form onSubmit={handleSubmit}>
          <input
            ref={nameInputRef}
            type="text"
            placeholder="Brukernavn"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            className="block w-full p-2 mb-3 bg-gray-700 rounded"
            required
          />
          <input
            type="email"
            placeholder="E-post"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="block w-full p-2 mb-3 bg-gray-700 rounded"
            required
          />
          <input
            type="password"
            placeholder="Passord"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            className="block w-full p-2 mb-3 bg-gray-700 rounded"
            required
          />
          <div className="flex justify-center gap-4">
            <button
              type="submit"
              className="px-4 py-2 text-white bg-blue-600 rounded hover:bg-blue-700"
            >
              Registrer
            </button>
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-white bg-gray-600 rounded hover:bg-gray-700"
            >
              Avbryt
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

// vue-frontend/app/modals/RegisterModal.vue
<script setup lang="ts">
import { ref, watch, nextTick } from "vue";
import { useRouter } from "#app";
import { registerUser } from "~/services/userService";

const props = defineProps<{
  open: boolean;
  onClose: () => void;
}>();

const router = useRouter();

const username = ref("");
const email = ref("");
const password = ref("");
const error = ref("");
const nameInputRef = ref<HTMLInputElement | null>(null);

async function handleSubmit(e: Event) {
  e.preventDefault();

  if (!username.value || !email.value || !password.value) {
    error.value = "Alle felt må fylles inn";
    return;
  }

  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailRegex.test(email.value)) {
    error.value = "Ugyldig e-postadresse";
    return;
  }

  try {
    await registerUser({
      username: username.value,
      email: email.value,
      password: password.value,
    });

    error.value = "";
    username.value = "";
    email.value = "";
    password.value = "";
    props.onClose();
    router.push("/");
  } catch (err) {
    console.error("Kunne ikke registrere bruker:", err);
    error.value = "Feil ved registrering av ny bruker";
  }
}

// Autofokus ved åpning
watch(
  () => props.open,
  async (isOpen) => {
    if (isOpen) {
      await nextTick();
      nameInputRef.value?.focus();
    }
  }
);
</script>

<template>
  <Teleport to="body">
    <div v-if="props.open" class="modal-overlay">
      <div
        class="w-[90%] sm:max-w-md md:max-w-lg p-8 text-center bg-gray-800 rounded-xl shadow-2xl border border-gray-700"
      >
        <h2 class="mb-4 text-2xl font-bold">Registrer ny bruker</h2>
        <p v-if="error" class="mb-2 text-red-500">{{ error }}</p>

        <form @submit="handleSubmit" class="space-y-4">
          <input
            ref="nameInputRef"
            type="text"
            placeholder="Brukernavn"
            v-model="username"
            class="block w-full p-3 bg-gray-700 rounded outline-none focus:ring-2 focus:ring-blue-500"
            required
          />

          <input
            type="email"
            placeholder="E-post"
            v-model="email"
            class="block w-full p-3 bg-gray-700 rounded outline-none focus:ring-2 focus:ring-blue-500"
            required
          />

          <input
            type="password"
            placeholder="Passord"
            v-model="password"
            class="block w-full p-3 bg-gray-700 rounded outline-none focus:ring-2 focus:ring-blue-500"
            required
          />

          <div class="flex justify-center gap-4 mt-4">
            <button
              type="submit"
              class="px-5 py-2 text-white bg-blue-600 rounded hover:bg-blue-700"
            >
              Registrer
            </button>
            <button
              type="button"
              @click="props.onClose"
              class="px-5 py-2 text-white bg-gray-600 rounded hover:bg-gray-700"
            >
              Avbryt
            </button>
          </div>
        </form>
      </div>
    </div>
  </Teleport>
</template>

<style scoped>
.modal-overlay {
  position: fixed !important;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: 9999;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: rgba(0, 0, 0, 0.6);
}
</style>
