// frontend/src/components/OrderList.tsx
"use client";
import { useEffect, useState } from "react";
import { getOrdersForUser } from "@/services/orderApi";
import { OrderDto } from "@/types/Order";
import OrderCard from "./OrderCard";

export default function OrderList() {
  const [orders, setOrders] = useState<OrderDto[]>([]);

  useEffect(() => {
    getOrdersForUser()
      .then(setOrders)
      .catch((err) => console.error("Kunne ikke hente ordrer:", err));
  }, []);

  if (orders.length === 0) {
    return <p>Du har ingen ordrer enda.</p>;
  }

  return (
    <section className="my-12">
      <h2 className="flex justify-center mb-6 text-2xl font-bold">
        Mine ordre
      </h2>
      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {orders.map((order) => (
          <OrderCard
            key={order.id}
            order={order}
            onStatusChange={(id, status) => {
              setOrders((prev) =>
                prev.map((o) => (o.id === id ? { ...o, status } : o))
              );
            }}
          />
        ))}
      </div>
    </section>
  );
}

// vue-frontend/app/components/OrderList.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { getOrdersForUser } from "~/services/orderService";
import type { OrderDto } from "~/types/order";
import OrderCard from "~/components/OrderCard.vue";

const orders = ref<OrderDto[]>([]);

onMounted(async () => {
  try {
    orders.value = await getOrdersForUser();
  } catch (err) {
    console.error("Kunne ikke hente ordrer:", err);
  }
});

function handleStatusChange(id: number, status: string) {
  orders.value = orders.value.map((o) => (o.id === id ? { ...o, status } : o));
}
</script>

<template>
  <section class="my-12">
    <h2 class="flex justify-center mb-6 text-2xl font-bold">Mine ordre</h2>

    <template v-if="orders.length === 0">
      <p>Du har ingen ordrer enda.</p>
    </template>

    <template v-else>
      <div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
        <OrderCard
          v-for="order in orders"
          :key="order.id"
          :order="order"
          :on-status-change="handleStatusChange"
        />
      </div>
    </template>
  </section>
</template>
